global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus' # prometheus is a source of metrics for services
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
    basic_auth:      #  password protected connection from Prometheus to Prometheus
      username_file: './.user'
      password_file: './.pwd'

#  - job_name: 'node' # Node Exporter provides metrics for the host
#    static_configs:
#      - targets: ['node-exporter:9100']
#    basic_auth:      #  password protected connection from Prometheus to Node Exporter
#      username_file: './.user'
#      password_file: './.pwd'

